name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Update README
        run: |-
          python main.py
          cat README.md

      - name: Update running
        run: |
          curl -H "Authorization: token ${{ secrets.METRICS_TOKEN }}" -O https://raw.githubusercontent.com/shensl4499/running_page/master/assets/github_2023.svg

      - name: generate contribution-grid-snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Commit and push if changed
        run: |-
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "ci: update profile (automatically)" || echo "nothing to commit"
          git push || echo "nothing to push"
